### ISSUE TITLE
multilang support?

### ISSUE THREAD

**Issue by foxpcteam** [jidaikobo-shibata/a11yc#1]
Hi,
why you didn't make this multilang support?

**Comment by jidaikobo-shibata** [comment]
Oh Sorry! I did not notice your comment.

I am planning multilang support.
Currently, by editing config file, you may use this program in English.
But this feature is in progress.

**Comment by jidaikobo-shibata** [comment]
English Version is here.
https://a11yc.com/validator/en/index.php
