### ISSUE TITLE
Not recognizing some language code

### ISSUE THREAD

**Issue by momdo** [jidaikobo-shibata/a11yc#2]
A11yc does not interpret BCP 47 language tags well.
For instance, giving following snippet, returns as error:

```
<span lang="ain">アシㇼパ</span>
```

**Comment by jidaikobo-shibata** [comment]
current version of a11yc's language check is created by misunderstanding of BCP 47.
So after my studying of BCP 47, I will fix this issue.

**Comment by jidaikobo-shibata** [comment]
Thank you for giving us a feedback. Currently Japanes Ainu language check is available!
