### ISSUE TITLE
Change validation to check on the web service name

### ISSUE THREAD

**Issue by momdo** [jidaikobo-shibata/a11yc#3]
バリデーションという語に、XMLでいうところの妥当性検証のようなニュワンスを感じるので、単にチェックぐらいにしてはどうでしょうか。

**Comment by jidaikobo-shibata** [comment]
そうですね。変えちゃってもいいかな。

**Comment by jidaikobo-shibata** [comment]
URLにも影響があり、さっさとやったほうがよい案件だったので、対応しました。僕自身「バリデーションというと、ちょっと違うなあ」と思っていたのもあります。

https://a11yc.com
https://a11yc.com/check/index.php
https://a11yc.com/check/en/index.php

旧URLからはリダイレクトしています。
https://a11yc.com/validator/index.php
https://a11yc.com/validator/en/index.php

ご意見ありがとうございました。
